Sources/KituraWebSocket/WebSocketConnection.swift

We are seeing crashes in Kitura-WebSocket unit tests because unowned self is sometimes being referenced after being reclaimed in a couple of places. We may need to change them to weak references instead.
See IBM-Swift/Kitura#988

unowned self in Kitura-WebSocket sometimes referenced after being reclaimed

---

Sources/KituraWebSocket/WSServerRequest.swift
Sources/KituraWebSocket/WebSocketConnection.swift
Tests/KituraWebSocketTests/BasicTests.swift
Tests/KituraWebSocketTests/KituraTest.swift
Tests/KituraWebSocketTests/TestWebSocketService.swift

Part of the Kitura-WebSocket Connection API is access to the ServerRequest that was to upgrade the original HTTP 1.1 connection into a WebSocket connection.
The original implementation simply saved a reference to the original ServerRequest from KituraNet. This is problematic as some of the underlying classes/structs of the KituraNet ServerRequest get released and/or reused causing problems. This was raised in IBM-Swift/Kitura-WebSocket#12.
This PR adds a class that is used to clone the KituraNet ServerRequest and is then used in the Kitura-WebSocket Connection API.
This has been unit tested on macOS and Linux with tests added to test the new ServerRequest implementation.

Prevent the Connection.request field from being freed

---

Sources/KituraWebSocket/WSSocketProcessor.swift
Sources/KituraWebSocket/WebSocketConnection.swift
Tests/KituraWebSocketTests/BasicTests.swift
Tests/KituraWebSocketTests/KituraTest.swift
Tests/KituraWebSocketTests/ProtocolErrorTests.swift
Tests/KituraWebSocketTests/TestWebSocketService.swift

Add tests to Kitura-WebSocket to improve the code coverage.
Fix issue with the "connected event handler" (WebSocketService.connected) being invoked before the response was sent to the websocket upgrade request. This prevented "connected event handler" from sending messages to the client.

Improve code coverage and enable sending of messages in "connected event handler"

---

Sources/KituraWebSocket/WSFrameParser.swift
Sources/KituraWebSocket/WebSocketConnection.swift
Sources/KituraWebSocket/WebSocketError.swift
Tests/KituraWebSocketTests/ProtocolErrorTests.swift

This pull request if to make our websockets server pass [Autobahn tests](https://github.com/crossbario/autobahn-testsuite). 
These changes make websockets pass:
Case 2.5 (oversized ping)
Case 3.* (Reserved bits are == 0)

pass ping and rsv tests

---

Sources/KituraWebSocket/WebSocketCloseReasonCode.swift
Sources/KituraWebSocket/WebSocketConnection.swift
Tests/KituraWebSocketTests/BasicTests.swift

Fixed a bug caused when i user sent a large code reason code.
This was caused by the server using Int16 instead of UInt16.
A test for user defined large input has been added and now passed.

fix: user defined close message

---

Sources/KituraWebSocket/WebSocketConnection.swift
Tests/KituraWebSocketTests/ProtocolErrorTests.swift

By the [websockets protocol](https://tools.ietf.org/html/rfc6455#section-5.4) control frames such as ping, close and pong cannot be fragmented. 
This means we should close if we receive a control frame which has a continuation.
Since pong and close will close already we have only changed ping.
This now passes autobahn test 5.1 and a test to check this has been added.

No fragmenting control frames

---

Sources/KituraWebSocket/WSFrame.swift
Sources/KituraWebSocket/WSFrameParser.swift

Replaces 'copyBytes(from:count:)' with 'copyMemory(from:byteCount:)' to silence swift 4.1 deprecation warnings.

Fix: Resolve deprecation warnings for swift 4.1

---

Sources/KituraWebSocket/WebSocketConnection.swift
Tests/KituraWebSocketTests/ProtocolErrorTests.swift

This pull request makes the websocket server close the connection on receiving invalid UTF-8 and return the error message:
Failed to convert received payload to UTF-8 String
A new test has been added which sends invalid utf-8 and expects to receive this error code.

close on invalid UTF-8

---

Sources/KituraWebSocket/WebSocketCloseReasonCode.swift
Sources/KituraWebSocket/WebSocketConnection.swift
Tests/KituraWebSocketTests/BasicTests.swift
Tests/KituraWebSocketTests/ProtocolErrorTests.swift

Pull request to make our web sockets pass autobahn tests 7.* regarding close codes.
reserved user close codes (1005, 1006) and undefined codes < 3000 will now return a protocol error. 
Close payloads can now not be longer than 125 bytes or equal to 1 byte as defined by the protocol
The close code provided by the server is now used to be sent back instead of just calculating it and then sending back .normal regardless.
Two Tests have been added and an existing test ha been change to check for the desired behavior.

Bad close codes

---

Sources/KituraWebSocket/WebSocketConnection.swift
Tests/KituraWebSocketTests/BasicTests.swift

Replaced the system for converting data to string.
Previously data had a null terminator added on the end and was converted to a pointer which was then used to read as a string up to the null terminator. If the user sent a null terminator in their string then their message would only be read up to that point.
Now the Data is converted straight to a utf8 string and sent on.
Test added to check this behavior.

accept null utf char

---

Sources/KituraWebSocket/WebSocketConnection.swift
Tests/KituraWebSocketTests/BasicTests.swift
Tests/KituraWebSocketTests/ProtocolErrorTests.swift

As part of passing Autobahn test suite, added feature to take user defined close message and check for valid UTF8 encoding.
Added two tests to check the functionality.
Added testNullCharacter to alltests
Renamed testUserDefinedCloseMessage to testUserDefinedCloseCode to distinguish tests

added user close message

---

AutobahnTests.md
README.md

Added a note to the readme stating our compliance to the Autobahn testsuite and linked to a document describing how to create a echoserver and run the tests against it.

add autobahn testsuite

---

Sources/KituraWebSocket/WebSocketConnection.swift

The connection must be dropped/closed with error code 1002 for an invalid operation code.

[websocket-nio]Close connection for invalid operation code

---

Sources/KituraWebSocket/WebSocketConnection.swift

[https://tools.ietf.org/html/rfc6455#section-5.5](url) specifies `All control frames MUST have a payload length of 125 bytes or less and MUST NOT be fragmented. `
For such control frames, errors are thrown by NIO websocket module and hence we must handle these errors.

Handle NIOWebSocketErrors

---

Sources/KituraWebSocket/WebSocketService.swift

The extension to WebSocketService with default implementation for connectionTimeout was internal meaning that when a user implemented this protocol they had to implement the change themselves. 
This pr makes the extension public.

Fix: make extension to WebSocketService public

---

Sources/KituraWebSocket/WebSocketConnection.swift

The connection timeout timer should ping twice during the connection timeout window. 
Currently it is only pinging once resulting in active connections being accidentally cleaned up.

fix: halved connection timeout ping time

---

Package.swift
Sources/KituraWebSocket/WSConnectionUpgradeFactory.swift
Sources/KituraWebSocket/WSServerRequest.swift
Sources/KituraWebSocket/WebSocket.swift
Sources/KituraWebSocket/WebSocketCloseReasonCode.swift
Sources/KituraWebSocket/WebSocketConnection.swift
Sources/KituraWebSocket/WebSocketError.swift
Tests/KituraWebSocketTests/BasicTests.swift
Tests/KituraWebSocketTests/ComplexTests.swift
Tests/KituraWebSocketTests/KituraTest+Frames.swift
Tests/KituraWebSocketTests/KituraTest.swift
Tests/KituraWebSocketTests/PrintLogger.swift
Tests/KituraWebSocketTests/ProtocolError.swift
Tests/KituraWebSocketTests/TestWebSocketService.swift
Tests/KituraWebSocketTests/UpgradeErrors.swift
Tests/LinuxMain.swift

This PR enforces Swift style and conventions based on https://github.com/realm/SwiftLint and violations for following rules has been fixed.
Closing Brace Spacing
Closure Spacing
Colon
Control Statement
Empty Parentheses with Trailing Closure
Empty Enum Arguments
Switch and Case Statement Alignment
Trailing Closure
Trailing Comma
Trailing Semicolon
Trailing Whitespace
Vertical Whitespace
Rules Ref: https://github.com/realm/SwiftLint/blob/master/Rules.md

[websocket-nio]Fix SwiftLint errors and warnings

---

.gitignore
Package@swift-4.0.swift
Package@swift-4.1.swift
Sources/CZlib/module.modulemap
Sources/CZlib/shim.h
Sources/KituraWebSocket/PermessageDeflate.swift
Sources/KituraWebSocket/PermessageDeflateCompressor.swift
Sources/KituraWebSocket/PermessageDeflateDecompressor.swift
Sources/KituraWebSocket/WSConnectionUpgradeFactory.swift
Sources/KituraWebSocket/WebSocketConnection.swift
Tests/KituraWebSocketTests/BasicTests.swift
Tests/KituraWebSocketTests/ComplexTests.swift
Tests/KituraWebSocketTests/InflaterDeflaterTests.swift
Tests/KituraWebSocketTests/KituraTest+Frames.swift
Tests/KituraWebSocketTests/KituraTest.swift
Tests/LinuxMain.swift

An initial implementation of websocket compression using `permessage-deflate` using zlib. 
Some TODOs:

Add websocket compression using permessage-deflate

---

Sources/KituraWebSocket/PermessageDeflate.swift
Sources/KituraWebSocket/PermessageDeflateCompressor.swift

This commit makes two changes. Firstly, client_max_window bits must not be returned in the negotiation response. Secondly, after deflating the payload, the last four octets need to be dropped.

[nio]autobahn: fixes for compression tests

---

Package.swift
Package@swift-4.0.swift
Package@swift-4.1.swift

Cryptor is used only in the Kitura-WebSocket tests in the client implementation. Moving it to the right dependency set.

[websocket-nio] make Cryptor only a test dependency
